### ISSUE TITLE
[Feature Request] Support password changing by admin and hiding login command in console

### ISSUE THREAD

**Issue by sandtechnology** [zigazajc007/Passky#2]
As the title, those two features is the basic thing which a authentication plugin should do.
I originally want to implement this and send a PR request, but I don't see any license there, so I make a Feature Request issue there.

**Comment by zigazajc007** [comment]
Hello,

I have just added the MIT License. So feel free to create your own PR.

**Comment by zigazajc007** [comment]
Thank you for your contribution. I have updated the plugin and put your GitHub username on the spigot as contributor.
