### ISSUE TITLE
Add support for spawning in non-logout location

### ISSUE THREAD

**Issue by donCESAR12345** [zigazajc007/Passky#9]
Please make the non logged-in players appear at the spawn point or somewhere else (configurable) so people can't get into other accounts and spoof the coordinates.

Once people log in, send them to where they were.

**Comment by zigazajc007** [comment]
Great idea thanks.

You can expect this feature to be implemented in the next update

**Comment by zigazajc007** [comment]
Hello,

I have implemented this feature, but it wasn't tested enough. So if you have time for testing, I would really appreciate that.

New version: https://cdn.rabbit-company.com/plugins/Passky/Passky-2.1.0.jar

**Comment by donCESAR12345** [comment]
I'll test it for a few days and notify any issue

**Comment by zigazajc007** [comment]
Thanks

Can you re-download the plugin: https://cdn.rabbit-company.com/plugins/Passky/Passky-2.1.0.jar

I have fixed this feature for players that Passky doesn't know their last location yet. So now it should also teleport for old players to their correct last location even if Passky doesn't have it saved yet.

**Comment by zigazajc007** [comment]
Hello,

Can you re-download the plugin: https://cdn.rabbit-company.com/plugins/Passky/Passky-2.1.0.jar

- I have made location_protection mandatory and removed algorithm for calculating damage (not needed anymore if logged out players will always be teleported to safe location (spawnpoint))
- Fixed location issue if players aren't registered yet
- Hunger level also won't change if players aren't logged in

**Comment by zigazajc007** [comment]
Passky 2.1.0 has been released.

Thanks again for your feature request and for helping with testing.

I will close this issue, but if you find a bug feel free to open a new one.
